import { Resend } from 'resend';

const resend = new Resend(process.env.RESEND_API_KEY);

function fmt(n) {
  return Number(n).toFixed(2);
}

export async function sendQuoteEmail({ clientName, clientEmail, quoteData, pdfBuffer, quoteId }) {
  const fromEmail = process.env.FROM_EMAIL || 'quotes@tradeos.com.au';
  const businessName = process.env.BUSINESS_NAME || '[Your Business Name]';

  const html = `
<div style="font-family:-apple-system,BlinkMacSystemFont,'Segoe UI',Arial,sans-serif;max-width:600px;margin:0 auto;background:#fff;">

  <div style="background:#1a1a1a;padding:24px 32px;">
    <span style="color:#E8521A;font-size:24px;font-weight:900;letter-spacing:-0.5px;">TradeOS</span>
  </div>

  <div style="padding:32px;">
    <h2 style="color:#1a1a1a;font-size:20px;margin-bottom:16px;">Your Quote is Ready</h2>

    <p style="color:#444;line-height:1.6;margin-bottom:12px;">Hi ${clientName},</p>
    <p style="color:#444;line-height:1.6;margin-bottom:24px;">
      Thank you for your enquiry. Please find your quote attached to this email (PDF).
    </p>

    <div style="background:#fdf4f0;border-left:4px solid #E8521A;padding:16px 20px;border-radius:0 6px 6px 0;margin-bottom:24px;">
      <table style="width:100%;border-collapse:collapse;">
        <tr>
          <td style="color:#666;font-size:12px;padding:3px 0;">Quote Reference</td>
          <td style="color:#1a1a1a;font-weight:700;font-size:12px;text-align:right;">${quoteId}</td>
        </tr>
        <tr>
          <td style="color:#666;font-size:12px;padding:3px 0;">Total (inc. GST)</td>
          <td style="color:#E8521A;font-weight:900;font-size:18px;text-align:right;">$${fmt(quoteData.totalIncGST)} AUD</td>
        </tr>
        <tr>
          <td style="color:#666;font-size:12px;padding:3px 0;">Valid for</td>
          <td style="color:#1a1a1a;font-weight:700;font-size:12px;text-align:right;">${quoteData.validDays || 30} days</td>
        </tr>
      </table>
    </div>

    <p style="color:#444;line-height:1.6;margin-bottom:24px;">${quoteData.jobSummary}</p>

    <p style="color:#444;line-height:1.6;">
      If you have any questions about this quote, please get in touch.<br><br>
      Kind regards,<br>
      <strong style="color:#1a1a1a;">${businessName}</strong>
    </p>
  </div>

  <div style="background:#f5f5f5;padding:16px 32px;text-align:center;">
    <p style="color:#aaa;font-size:11px;margin:0;">
      Quote generated by <a href="https://tradeos.com.au" style="color:#E8521A;text-decoration:none;">TradeOS</a>
      &mdash; Professional Trade Quoting
    </p>
  </div>

</div>`;

  await resend.emails.send({
    from: fromEmail,
    to: clientEmail,
    subject: `Your Quote from ${businessName} — ${quoteId}`,
    html,
    attachments: [
      {
        filename: `Quote-${quoteId}.pdf`,
        content: pdfBuffer.toString('base64'),
      },
    ],
  });
}
