// Changed: New file — Quote history screen (Change 6)
// Fetches past quotes from Supabase, shows list, tap to view details
import { useState, useEffect } from 'react';

function fmt(n) {
  return Number(n).toLocaleString('en-AU', { minimumFractionDigits: 2, maximumFractionDigits: 2 });
}

function formatDate(dateStr) {
  const d = new Date(dateStr);
  return d.toLocaleDateString('en-AU', { day: '2-digit', month: 'short', year: 'numeric' });
}

export default function QuoteHistory({ businessName, apiBase, onBack }) {
  const [quotes, setQuotes] = useState([]);
  const [loading, setLoading] = useState(true);
  const [selected, setSelected] = useState(null);

  useEffect(() => {
    if (!businessName) {
      setLoading(false);
      return;
    }

    fetch(`${apiBase}/api/quotes?businessName=${encodeURIComponent(businessName)}`)
      .then((r) => r.json())
      .then((data) => setQuotes(data.quotes || []))
      .catch(() => setQuotes([]))
      .finally(() => setLoading(false));
  }, [businessName, apiBase]);

  // ─── Detail view for a selected quote ───
  if (selected) {
    const q = selected;
    const items = typeof q.items === 'string' ? JSON.parse(q.items) : q.items;

    return (
      <div>
        <button className="back-link" onClick={() => setSelected(null)}>
          ← Back to history
        </button>

        <div className="quote-summary">
          <div className="quote-summary-header">
            <div>
              <div className="quote-id">{q.quote_number}</div>
              <div style={{ color: '#777', fontSize: '11px', marginTop: '4px' }}>
                {q.client_name}
              </div>
            </div>
            <div style={{ textAlign: 'right' }}>
              <div className="quote-total">${fmt(q.total)}</div>
              <div className="quote-total-label">inc. GST · AUD</div>
            </div>
          </div>

          {items && (
            <div className="items-list">
              {items.map((item, i) => (
                <div className="item-row" key={i}>
                  <span className="item-desc">
                    {item.description}
                    <span style={{ display: 'block', fontSize: '12px', color: '#999', marginTop: '2px' }}>
                      {item.quantity} {item.unit} × ${fmt(item.unitPrice)}
                    </span>
                  </span>
                  <span className="item-price">${fmt(item.subtotal)}</span>
                </div>
              ))}
            </div>
          )}

          <div className="gst-row">
            <span>Subtotal (ex. GST)</span>
            <span>${fmt(q.subtotal)}</span>
          </div>
          <div className="gst-row" style={{ borderBottom: '1px solid #DDE3EF' }}>
            <span>GST (10%)</span>
            <span>${fmt(q.gst)}</span>
          </div>
          <div className="total-row-ui">
            <span>TOTAL</span>
            <span>${fmt(q.total)} AUD</span>
          </div>
        </div>

        <div className="card" style={{ fontSize: '13px', color: '#6B7280', lineHeight: '1.6' }}>
          <strong style={{ color: '#1a1a1a', display: 'block', marginBottom: '4px' }}>Client</strong>
          {q.client_name} · {q.client_email}
          <br />
          <strong style={{ color: '#1a1a1a', display: 'block', marginBottom: '4px', marginTop: '10px' }}>Date</strong>
          {formatDate(q.created_at)}
        </div>
      </div>
    );
  }

  // ─── List view ───
  return (
    <div>
      <div className="form-header-row">
        <h1>
          <span className="heading-icon">📋</span>
          Quote History
        </h1>
        <button className="back-link" onClick={onBack}>
          ← New Quote
        </button>
      </div>
      <p className="subheading">
        All quotes generated by {businessName || 'your business'}.
      </p>

      {loading && (
        <div className="card" style={{ textAlign: 'center', padding: '32px' }}>
          <div className="spinner-dark" style={{ margin: '0 auto 12px', width: '32px', height: '32px', borderWidth: '3px', borderTopColor: 'var(--blue)', borderColor: 'var(--border)' }} />
          Loading…
        </div>
      )}

      {!loading && quotes.length === 0 && (
        <div className="card" style={{ textAlign: 'center', padding: '40px 20px' }}>
          <div style={{ fontSize: '32px', marginBottom: '12px' }}>📭</div>
          <p style={{ color: '#6B7280', fontSize: '14px' }}>
            No quotes yet. Generate your first quote above.
          </p>
        </div>
      )}

      {!loading && quotes.length > 0 && (
        <div className="history-list">
          {quotes.map((q) => (
            <button
              className="history-card"
              key={q.id || q.quote_number}
              onClick={() => setSelected(q)}
            >
              <div className="history-left">
                <span className="history-date">{formatDate(q.created_at)}</span>
                <span className="history-name">{q.client_name}</span>
              </div>
              <div className="history-right">
                <span className="history-amount">${fmt(q.total)}</span>
                <span className="history-qid">{q.quote_number}</span>
              </div>
            </button>
          ))}
        </div>
      )}
    </div>
  );
}
